Category.create(name: 'Personal')
Category.create(name: 'Work')
Category.create(name: 'Housekeeping')
Category.create(name: 'Relationships')
Category.create(name: 'Healthy Eating')
Category.create(name: 'Career Development')
Category.create(name: 'Networking')
Category.create(name: 'Social')
Category.create(name: 'Exercise')
Category.create(name: 'Other')
Category.create(name: 'Project Deadlines')
Category.create(name: 'LivingSpace')
Category.create(name: 'Bathroom')
Category.create(name: 'Kitchen')
